## NumPy (https://docs.scipy.org/doc/numpy/release.html)

In [76]:
import numpy as np
from scipy import optimize
import matplotlib.pyplot as plt

## Vector

In [77]:
# declare
x = np.array([1,2,3])
y = np.array([4,5,6])
print("DECLARE")
print("x: ",x)
print("y: ",y)
print()

# arithmetic (Fortranに似てる)
print("ARITHMETIC")
print("+: ",x+y)
print("-: ",x-y)
print("*: ",x*y)
print("/: ",x/y)
print("**: ",x**y)
print("+1: ",x+1)
print()

# functions (Fortranに似てる)
print("FUNCTIONS")
print("sin: ",np.sin(x))
print("cos: ",np.cos(x))
print("exp: ",np.exp(x))
print("log: ",np.log(x))
print("etc...")

DECLARE
x:  [1 2 3]
y:  [4 5 6]

ARITHMETIC
+:  [5 7 9]
-:  [-3 -3 -3]
*:  [ 4 10 18]
/:  [0.25 0.4  0.5 ]
**:  [  1  32 729]
+1:  [2 3 4]

FUNCTIONS
sin:  [0.84147098 0.90929743 0.14112001]
cos:  [ 0.54030231 -0.41614684 -0.9899925 ]
exp:  [ 2.71828183  7.3890561  20.08553692]
log:  [0.         0.69314718 1.09861229]
etc...


In [78]:
# dot product
print("DOT PRODUCT")
d = np.dot(x,y)
print(d)
d = x.dot(y)
print(d)
print()

# cross product
print("CROSS PRODUCT")
c = np.cross(x,y)
print(c)
print()

DOT PRODUCT
32
32

CROSS PRODUCT
[-3  6 -3]



In [79]:
# shallow copy (Fortranと違う)
x = np.array([1,2,3])
y = np.array([4,5,6])
print("SHALLOW COPY")
print("original")
print("x: ",x)
print("y: ",y)
print()
x = y
print("x = y")
print("x: ",x)
print("y: ",y)
print()
y[1] = -1
print("y[1] = -1")
print("x: ",x)
print("y: ",y)
print()

# deep copy
x = np.array([1,2,3])
y = np.array([4,5,6])
print("DEEP COPY")
print("original")
print("x: ",x)
print("y: ",y)
print()
x = np.copy(y)
print("x = np.copy(y)")
print("x: ",x)
print("y: ",y)
print()
y[1] = -1
print("y[1] = -1")
print("x: ",x)
print("y: ",y)
print()

# ただし、配列の形状がいびつな場合はcopyがうまくいかず、参照渡しとなる。
# 配列の形状がいびつな場合でdeep copyをしたい場合は、
# import copyして、x = copy.deepcopy(y)とする。

SHALLOW COPY
original
x:  [1 2 3]
y:  [4 5 6]

x = y
x:  [4 5 6]
y:  [4 5 6]

y[1] = -1
x:  [ 4 -1  6]
y:  [ 4 -1  6]

DEEP COPY
original
x:  [1 2 3]
y:  [4 5 6]

x = np.copy(y)
x:  [4 5 6]
y:  [4 5 6]

y[1] = -1
x:  [4 5 6]
y:  [ 4 -1  6]



## Matrix

In [80]:
# declare
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5,6],[7,8,9]])
print("DECLARE")
print("a: ",a)
print("b: ",b)
print()

# arithmetic (Fortranに似てる)
print("ARITHMETIC")
print("+: ",a+b)
print("-: ",a-b)
print("*: ",a*b)
print("/: ",a/b)
print("**: ",a**b)
print("+1: ",a+1)
print()

# functions (Fortranに似てる)
print("FUNCTIONS")
print("sin: ",np.sin(a))
print("cos: ",np.cos(a))
print("exp: ",np.exp(a))
print("log: ",np.log(a))
print("etc...")

DECLARE
a:  [[1 2 3]
 [4 5 6]]
b:  [[4 5 6]
 [7 8 9]]

ARITHMETIC
+:  [[ 5  7  9]
 [11 13 15]]
-:  [[-3 -3 -3]
 [-3 -3 -3]]
*:  [[ 4 10 18]
 [28 40 54]]
/:  [[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]
**:  [[       1       32      729]
 [   16384   390625 10077696]]
+1:  [[2 3 4]
 [5 6 7]]

FUNCTIONS
sin:  [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
cos:  [[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
exp:  [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
log:  [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
etc...


In [81]:
# reshape
c = np.arange(24)
print("c: ",c)
print("c.reshape([3,8]): ",c.reshape([3,8]))
print("c.reshape(3,8): ",c.reshape(3,8))
print("np.reshape(c,[3,8]): ",np.reshape(c,[3,8]))
# np.reshape(c,3,8)はダメ
print("c.reshape(3,-1): ",c.reshape(3,-1))
# -1を指定すると自動で形状を計算してくれる

# 引数にorder='F'やorder='C'を入れると、
# 配列の順序をFortran式かC言語式として指定できる。
# defaultはorder='C'。

c:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
c.reshape([3,8]):  [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
c.reshape(3,8):  [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
np.reshape(c,[3,8]):  [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
c.reshape(3,-1):  [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [82]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5,6],[7,8,9]])
print("a: ",a)
print("b: ",b)
print()

# transpose
print("TRANSPOSE")
print("b.T: ",b.T)
print()

# matrix multiply
print("MATRIX MULTIPLY")
m = np.dot(a,b.T)
print("np.dot(a,b.T): ",m)
m = a.dot(b.T)
print("a.dot(b.T): ",m)
print()

# trace
print("TRACE")
print("np.trace(m): ",np.trace(m))
print()

# determinant
print("DETERMINANT")
print("np.linalg.det(m): ",np.linalg.det(m))
print()

# inverse
print("INVERSE")
print("np.linalg.inv(m): ",np.linalg.inv(m))
print("np.matrix(m).I: ",np.matrix(m).I)
print()

a:  [[1 2 3]
 [4 5 6]]
b:  [[4 5 6]
 [7 8 9]]

TRANSPOSE
b.T:  [[4 7]
 [5 8]
 [6 9]]

MATRIX MULTIPLY
np.dot(a,b.T):  [[ 32  50]
 [ 77 122]]
a.dot(b.T):  [[ 32  50]
 [ 77 122]]

TRACE
np.trace(m):  154

DETERMINANT
np.linalg.det(m):  54.00000000000022

INVERSE
np.linalg.inv(m):  [[ 2.25925926 -0.92592593]
 [-1.42592593  0.59259259]]
np.matrix(m).I:  [[ 2.25925926 -0.92592593]
 [-1.42592593  0.59259259]]



## Examples

In [107]:
n = 10
a = n*np.random.rand()
b = n*np.random.rand()
x = np.linspace(0,n,n)
y = a*x + b + 0.5*n*(np.random.rand(n) - np.random.rand(n))
print("x: ",x)
print("y: ",y)
print()
plt.plot(x,y,".",c="b",label="data")

# answer
print("a (true): ",a)
print("b (true): ",b)
print()
plt.plot(x,a*x+b,"-",c="r",label="true")

# fitting (manual1)
mx = np.average(x)
my = np.mean(y)
mx2 = np.dot(x,x)/n
mxy = np.sum(x*y)/n
den = mx2 - mx*mx
p = (mxy-mx*my)/den
q = my-a*mx
print("a (manual1): ",p)
print("b (manual1): ",q)
print()
plt.plot(x,p*x+q,"-",c="g",label="manual1")

# fitting (manual2)
m = np.array([[mx2,mx],[mx,1]])
s = np.dot(np.linalg.inv(m),np.array([mxy,my]))
p = s[0]
q = s[1]
print("a (manual2): ",p)
print("b (manual2): ",q)
print()
plt.plot(x,p*x+q,"-",c="orange",label="manual2")

# fitting (polyfit)
p,q = np.polyfit(x,y,1)
print("a (plyfit): ",p)
print("b (plyfit): ",q)
print()
plt.plot(x,p*x+q,"-",c="indigo",label="polyfit")

plt.legend(loc="best")
plt.show()

### SciPy ###

def f(p,x,y):
    return y - (p[0]*x+p[1])

def g(x,a,b):
    return a*x + b

# fitting (optimize.leastsq)
s,t = optimize.leastsq(f,[n/2,n/2],args=(x,y))
p = s[0]
q = s[1]
print("a (leastsq): ",p)
print("b (leastsq): ",q)
print()

# fitting (optimize.curve_fit)
s,t = optimize.curve_fit(g,x,y)
p = s[0]
q = s[1]
print("a (curve_fit): ",p)
print("b (curve_fit): ",q)
print()

x:  [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
y:  [ 4.14726336  6.65419906 12.02775871 14.2988312  22.76262356 33.89135187
 35.62610147 43.33324181 46.89149995 56.05065598]

a (true):  5.145131941950789
b (true):  0.8602792890530064

a (manual1):  5.347797787302415
b (manual1):  1.8426929881377205

a (manual2):  5.347797787302419
b (manual2):  0.8293637613795681

a (plyfit):  5.347797787302413
b (plyfit):  0.8293637613795921



a (leastsq):  5.347797784190197
b (leastsq):  0.8293637736185175

a (curve_fit):  5.347797758141791
b (curve_fit):  0.8293639658002253

