# Read from text data

In [58]:
import numpy as np

filename="data.txt"

## python mode

### f.read()

In [59]:
f=open(filename)
all_data=f.read()
f.close()

print(all_data)
print(all_data.split())

This is a test text data for python-seminar.
Name Year Lab Comment
Sato AP Sato Paleomagne
Ito D1 Iizuka Geochem
Enomoto D1 Iizuka Geochem
Ue M2 Kawai Waveform Inversion
Okuda M2 Kawai Friction
Yoshida M1 Wallis Rheology
Fukuda M1 AORI Climate Simulation
Index Jpyear ADyear
J 30 2019 2542
I 29 2018 1345
H 28 2017 654
G 27 2016 14585
F 26 2015 315
E 25 2014 94
D 24 2013 13465
C 23 2012 4572
B 22 2011 9785
A 21 2010 245
30 2019 2542
29 2018 1345
28 2017 654
27 2016 14585
26 2015 315
25 2014 94
24 2013 13465
23 2012 4572
22 2011 9785
21 2010 245

['This', 'is', 'a', 'test', 'text', 'data', 'for', 'python-seminar.', 'Name', 'Year', 'Lab', 'Comment', 'Sato', 'AP', 'Sato', 'Paleomagne', 'Ito', 'D1', 'Iizuka', 'Geochem', 'Enomoto', 'D1', 'Iizuka', 'Geochem', 'Ue', 'M2', 'Kawai', 'Waveform', 'Inversion', 'Okuda', 'M2', 'Kawai', 'Friction', 'Yoshida', 'M1', 'Wallis', 'Rheology', 'Fukuda', 'M1', 'AORI', 'Climate', 'Simulation', 'Index', 'Jpyear', 'ADyear', 'J', '30', '2019', '2542', 'I', '29', '

### f.readlines()

In [63]:
f=open(filename)
all_line_data=f.readlines()
f.close()

print(all_line_data)

print("---------------")
for i in range (len(all_line_data)):
    print (all_line_data[i].split())
    
print("---------------")
float_data_1=np.empty((10,3))
for i in range (10):
    for j in range (3):
        float_data[i][j]=float(all_line_data[i+10].split()[j+1]) #先頭列の文字をはじいた上で数値データのみをndarray化する例
print(float_data)

['This is a test text data for python-seminar.\n', 'Name Year Lab Comment\n', 'Sato AP Sato Paleomagne\n', 'Ito D1 Iizuka Geochem\n', 'Enomoto D1 Iizuka Geochem\n', 'Ue M2 Kawai Waveform Inversion\n', 'Okuda M2 Kawai Friction\n', 'Yoshida M1 Wallis Rheology\n', 'Fukuda M1 AORI Climate Simulation\n', 'Index Jpyear ADyear\n', 'J 30 2019 2542\n', 'I 29 2018 1345\n', 'H 28 2017 654\n', 'G 27 2016 14585\n', 'F 26 2015 315\n', 'E 25 2014 94\n', 'D 24 2013 13465\n', 'C 23 2012 4572\n', 'B 22 2011 9785\n', 'A 21 2010 245\n', '30 2019 2542\n', '29 2018 1345\n', '28 2017 654\n', '27 2016 14585\n', '26 2015 315\n', '25 2014 94\n', '24 2013 13465\n', '23 2012 4572\n', '22 2011 9785\n', '21 2010 245\n']
---------------
['This', 'is', 'a', 'test', 'text', 'data', 'for', 'python-seminar.']
['Name', 'Year', 'Lab', 'Comment']
['Sato', 'AP', 'Sato', 'Paleomagne']
['Ito', 'D1', 'Iizuka', 'Geochem']
['Enomoto', 'D1', 'Iizuka', 'Geochem']
['Ue', 'M2', 'Kawai', 'Waveform', 'Inversion']
['Okuda', 'M2', 'Kawa

### f.readline()

In [61]:
f=open(filename)
one_line_data=f.readline()

while one_line_data:
    print(one_line_data)
    one_line_data=f.readline()
    
f.close()

This is a test text data for python-seminar.

Name Year Lab Comment

Sato AP Sato Paleomagne

Ito D1 Iizuka Geochem

Enomoto D1 Iizuka Geochem

Ue M2 Kawai Waveform Inversion

Okuda M2 Kawai Friction

Yoshida M1 Wallis Rheology

Fukuda M1 AORI Climate Simulation

Index Jpyear ADyear

J 30 2019 2542

I 29 2018 1345

H 28 2017 654

G 27 2016 14585

F 26 2015 315

E 25 2014 94

D 24 2013 13465

C 23 2012 4572

B 22 2011 9785

A 21 2010 245

30 2019 2542

29 2018 1345

28 2017 654

27 2016 14585

26 2015 315

25 2014 94

24 2013 13465

23 2012 4572

22 2011 9785

21 2010 245



## NumPy np.loadtxt

In [62]:
all_line_data_numpy=np.loadtxt(filename,skiprows=20) #文字列がないところまで行をスキップする
print(all_line_data_numpy)

[[   30.  2019.  2542.]
 [   29.  2018.  1345.]
 [   28.  2017.   654.]
 [   27.  2016. 14585.]
 [   26.  2015.   315.]
 [   25.  2014.    94.]
 [   24.  2013. 13465.]
 [   23.  2012.  4572.]
 [   22.  2011.  9785.]
 [   21.  2010.   245.]]
