## NumPy (https://docs.scipy.org/doc/numpy/release.html)

In [36]:
import numpy as np
import matplotlib.pyplot as plt

## Vector

In [45]:
# declare
x = np.array([1,2,3])
y = np.array([4,5,6])
print("DECLARE")
print("x: ",x)
print("y: ",y)
print()

# arithmetic (Fortranに似てる)
print("ARITHMETIC")
print("+: ",x+y)
print("-: ",x-y)
print("*: ",x*y)
print("/: ",x/y)
print("**: ",x**y)
print("+1: ",x+1)
print()

# functions (Fortranに似てる)
print("FUNCTIONS")
print("sin: ",np.sin(x))
print("cos: ",np.cos(x))
print("exp: ",np.exp(x))
print("log: ",np.log(x))
print("etc...")

DECLARE
x:  [1 2 3]
y:  [4 5 6]

ARITHMETIC
+:  [5 7 9]
-:  [-3 -3 -3]
*:  [ 4 10 18]
/:  [0.25 0.4  0.5 ]
**:  [  1  32 729]
+1:  [2 3 4]

FUNCTIONS
sin:  [0.84147098 0.90929743 0.14112001]
cos:  [ 0.54030231 -0.41614684 -0.9899925 ]
exp:  [ 2.71828183  7.3890561  20.08553692]
log:  [0.         0.69314718 1.09861229]
etc...


In [38]:
# dot product
print("DOT PRODUCT")
d = np.dot(x,y)
print(d)
d = x.dot(y)
print(d)
print()

# cross product
print("CROSS PRODUCT")
c = np.cross(x,y)
print(c)
print()

DOT PRODUCT
32
32

CROSS PRODUCT
[-3  6 -3]



In [42]:
# shallow copy (Fortranと違う)
x = np.array([1,2,3])
y = np.array([4,5,6])
print("SHALLOW COPY")
print("original")
print("x: ",x)
print("y: ",y)
print()
x = y
print("x = y")
print("x: ",x)
print("y: ",y)
print()
y[1] = -1
print("y[1] = -1")
print("x: ",x)
print("y: ",y)
print()

# deep copy
x = np.array([1,2,3])
y = np.array([4,5,6])
print("DEEP COPY")
print("original")
print("x: ",x)
print("y: ",y)
print()
x = np.copy(y)
print("x = np.copy(y)")
print("x: ",x)
print("y: ",y)
print()
y[1] = -1
print("y[1] = -1")
print("x: ",x)
print("y: ",y)
print()

# ただし、配列の形状がいびつな場合はcopyがうまくいかず、参照渡しとなる。
# 配列の形状がいびつな場合でdeep copyをしたい場合は、
# import copyして、x = copy.deepcopy(y)とする。

SHALLOW COPY
original
x:  [1 2 3]
y:  [4 5 6]

x = y
x:  [4 5 6]
y:  [4 5 6]

y[1] = -1
x:  [ 4 -1  6]
y:  [ 4 -1  6]

DEEP COPY
original
x:  [1 2 3]
y:  [4 5 6]

x = np.copy(y)
x:  [4 5 6]
y:  [4 5 6]

y[1] = -1
x:  [4 5 6]
y:  [ 4 -1  6]



## Matrix

In [47]:
# declare
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5,6],[7,8,9]])
print("DECLARE")
print("a: ",a)
print("b: ",b)
print()

# arithmetic (Fortranに似てる)
print("ARITHMETIC")
print("+: ",a+b)
print("-: ",a-b)
print("*: ",a*b)
print("/: ",a/b)
print("**: ",a**b)
print("+1: ",a+1)
print()

# functions (Fortranに似てる)
print("FUNCTIONS")
print("sin: ",np.sin(a))
print("cos: ",np.cos(a))
print("exp: ",np.exp(a))
print("log: ",np.log(a))
print("etc...")

DECLARE
a:  [[1 2 3]
 [4 5 6]]
b:  [[4 5 6]
 [7 8 9]]

ARITHMETIC
+:  [[ 5  7  9]
 [11 13 15]]
-:  [[-3 -3 -3]
 [-3 -3 -3]]
*:  [[ 4 10 18]
 [28 40 54]]
/:  [[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]
**:  [[       1       32      729]
 [   16384   390625 10077696]]
+1:  [[2 3 4]
 [5 6 7]]

FUNCTIONS
sin:  [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
cos:  [[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
exp:  [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
log:  [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
etc...


In [53]:
# reshape
c = np.arange(24)
print("c: ",c)
print("c.reshape([3,8]): ",c.reshape([3,8]))
print("c.reshape(3,8): ",c.reshape(3,8))
print("np.reshape(c,[3,8]): ",np.reshape(c,[3,8]))
# np.reshape(c,3,8)はダメ
print("c.reshape(3,-1): ",c.reshape(3,-1))
# -1を指定すると自動で形状を計算してくれる

# 引数にorder='F'やorder='C'を入れると、
# 配列の順序をFortran式かC言語式として指定できる。
# defaultはorder='C'。

c:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
c.reshape([3,8]):  [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
c.reshape(3,8):  [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
np.reshape(c,[3,8]):  [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
c.reshape(3,-1):  [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [56]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5,6],[7,8,9]])
print("a: ",a)
print("b: ",b)
print()

# transpose
print("TRANSPOSE")
print("b.T: ",b.T)
print()

# matrix multiply
print("MATRIX MULTIPLY")
m = np.dot(b.T,a)
print("m: ",m)
print()

a:  [[1 2 3]
 [4 5 6]]
b:  [[4 5 6]
 [7 8 9]]

TRANSPOSE
b.T:  [[4 7]
 [5 8]
 [6 9]]

MATRIX MULTIPLY
m:  [[32 43 54]
 [37 50 63]
 [42 57 72]]

